### PR TITLE
package.json: require nodejs 16 or higher

### LINKED ISSUE #791: make: *** [Makefile:93: dist/manifest.json] Error 9
Trying to build on a fresh Ubuntu 22.04.5 systemd-nspawn container using the provided instructions ends up with the same error as [this comment](https://github.com/cockpit-project/cockpit-files/issues/596#issuecomment-2227096430) on another issue:

```
build@jammy:~/cockpit-files$ make
remote: Enumerating objects: 1405, done.
remote: Counting objects: 100% (1405/1405), done.
remote: Compressing objects: 100% (1212/1212), done.
remote: Total 1405 (delta 211), reused 696 (delta 110), pack-reused 0 (from 0)
Receiving objects: 100% (1405/1405), 7.32 MiB | 10.35 MiB/s, done.
Resolving deltas: 100% (211/211), done.
git archive 'fe196082855cd53d3fe9c4da91048b0a2ade6fe1^{tree}' -- pkg/lib test/common test/static-code tools/node-modules  | tar x
make package-lock.json && NODE_ENV= ./build.js
make[1]: Entering directory '/home/build/cockpit-files'
tools/node-modules make_package_lock_json
  FETCH    node_modules  [ref: 4d47b53c43852c9528a0a84f69f857aaab6e5fff]
  REMOVE   node_modules
  CLONE    node_modules  [ref: 4d47b53c43852c9528a0a84f69f857aaab6e5fff]
  COPY     package-lock.json
make[1]: Leaving directory '/home/build/cockpit-files'
node: bad option: --import
make: *** [Makefile:93: dist/manifest.json] Error 9
```

node version is 12.22.9~dfsg-1ubuntu3.6

Please let me know if you need more info and thanks for developing this cockpit app!

### PR DESCRIPTION
**Pull request by jelly**
Copied from starter-kit.

Hopefully avoids issues like https://github.com/cockpit-project/cockpit-files/issues/791

Fixes #791

### CODE REVIEW

**Comment by martinpitt** [comment]
Needs a node_modules refresh. I *think* it will fail with the workflow and the label due to permission errors, but *maybe* the "maintainers are allowed" magic makes this work :magic_wand:

**Comment by jelly** [comment]
> Needs a node_modules refresh. I _think_ it will fail with the workflow and the label due to permission errors, but _maybe_ the "maintainers are allowed" magic makes this work 🪄

Yeah, forgot about that. Fixed.

**Comment by allisonkarlitskaya** [comment]
According to https://nodejs.org/en/about/previous-releases 16 is no longer supported.  We should take a depend on at least 18.  We need it for `--import`, as well:  https://nodejs.org/api/cli.html#--importmodule

**Comment by martinpitt** [comment]
Ack -- let's bump to 18 then. Also, good to know that the node-modules label works fine for our forks!

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
