### PR TITLE
Various test fixes / maintainence

### PR DESCRIPTION
**Pull request by jelly**
The test was flaky as changing the directory didn't wait for the state to fully sync so a paste would paste in the previous directory.

Additionally add a check that after pasting going back to the original folder still shows the copied file.

Enable the upload test for debian-testing as we have Cockpit > 311 now.

### CODE REVIEW

**Comment by jelly** [comment]
Ok lol, not done yet!

**Comment by jelly** [comment]
One left on rawhide:
```
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-application", line 1060, in testCopyPaste
    b.wait_visible("[data-item='copyDir']")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 658, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 649, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("[data-item='copyDir']")): Uncaught (in promise) Error: condition did not become true
```

**Comment by jelly** [comment]
Not sure what the download failure is about in Fedora-39. Going to retry that as this is already a massive improvement in flakyness.

**Review by martinpitt — APPROVED** [review]
Thanks! Indeed `wait_not_present()` is a no-op/wrong/buggy in all but the most carefully crafted situations. In particular, it just can't work right after a click or go().

**Pull request merged**
