### PR TITLE
package.json: drop unused devDependency on deep-equal

### PR DESCRIPTION
**Pull request by jelly**
Nothing in Files uses this.

### CODE REVIEW

**Comment by martinpitt** [comment]
I suggest doing a cockpit lib bump first to include the migration to dequal, and then put that into `dependencies`. As a devDependency it's indeed wrong.

**Comment by jelly** [comment]
> I suggest doing a cockpit lib bump first to include the migration to dequal, and then put that into `dependencies`. As a devDependency it's indeed wrong.

Hmm but it is not needed, the issue here is that we run `tsc` on `pkg/lib` in cockpit plugins. @allisonkarlitskaya mentioned this a few days ago in standup :)

**Comment by jelly** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/20664 which partially fixes it, but as we import `hooks.ts` we still need to know about `deep-equal` sadly although we don't use anything which uses `deep-equal`.

```
[jelle@t14s][~/projects/cockpit-files]%./test/static-code
not ok 10 /static-code/test-typescript
# pkg/lib/hooks.ts(22,24): error TS7016: Could not find a declaration file for module 'deep-equal'. '/home/jelle/projects/cockpit-files/node_modules/deep-equal/index.js' implicitly has an 'any' type.
#   Try `npm i --save-dev @types/deep-equal` if it exists or add a new declaration (.d.ts) file containing `declare module 'deep-equal';`
```

This feels very annoying as it means yet another `devDependency` and yet more churn of keeping it updated.

**Comment by allisonkarlitskaya** [comment]
I think this is superseded by #603.

**Pull request closed without merging**
