### PR TITLE
packit.yaml: run tests on a different architecture (aarch64)

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
Nice! (Obviously tests have the last word)

**Comment by martinpitt** [comment]
OK, it reproduces the koji failure, so easier to iterate here.

**Comment by jelly** [comment]
> OK, it reproduces the koji failure, so easier to iterate here.

Yup, time to figure out why it works in podman/cockpit :)

**Comment by jelly** [comment]
So naively I tried to just remove the x64 binary, but that breaks package.json
```
[root@fedora-aarch64-test cockpit-files]# ./build.js

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [TransformError]: The package "@esbuild/linux-arm64" could not be found, and is needed by esbuild.
```

**Comment by jelly** [comment]
So nuking the node_modules and running `npm install` again works:

```
[root@fedora-aarch64-test cockpit-files]# rm -rf node_modules
[root@fedora-aarch64-test cockpit-files]# npm install
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 467 packages, and audited 468 packages in 37s

166 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[root@fedora-aarch64-test cockpit-files]# ./build.js
true
```

So it seems sadly that node_modules are $arch dependent.

```
[root@fedora-aarch64-test cockpit-files]# ls "node_modules/@esbuild"
[root@fedora-aarch64-test cockpit-files]# ls "node_modules.orig/@esbuild"
linux-x64
```

**Comment by jelly** [comment]
Ah, so I read the hint again:
```
 Or you could consider using yarn
instead of npm which has built-in support for installing a package on multiple
platforms simultaneously.
```

Everything is pretty much summed up here https://esbuild.github.io/getting-started/#simultaneous-platforms

**Comment by jelly** [comment]
This is now more or less resolved as we package the bundled JS. But @martinpitt should we still test on ARM, it doesn't really hurt us and might find interesting issues with upload?

**Comment by martinpitt** [comment]
@jelly Yes, agreed -- these sometimes find funny bugs, and just the first commit here should work fine now? (at least wrt. the build system)

**Comment by jelly** [comment]
> @jelly Yes, agreed -- these sometimes find funny bugs, and just the first commit here should work fine now? (at least wrt. the build system)

:+1:  re-pushed, this should go green :crossed_fingers:

**Pull request merged**
