### PR TITLE
Add pixel tests

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by jelly** [comment]
```
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-application", line 1433, in testFileTypes
    b.assert_pixels("#folder-view", "icon-list-view")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1272, in assert_pixels
    self.assert_pixels_in_current_layout(selector, key, ignore=ignore,
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1135, in assert_pixels_in_current_layout
    raise SystemError("Pixel test references are missing, please run: test/common/pixel-tests pull")
SystemError: Pixel test references are missing, please run: test/common/pixel-tests pull
```

**Comment by jelly** [comment]
**sigh** I missed some makefile changes and noticed our tarball creation is very much different from podman which also excludes `.in`.

**Comment by jelly** [comment]
Pixel tests are there now :+1:  now just flaky pixel tests left :-1:

**Review by martinpitt — APPROVED** [review]
Yay! :camera_flash:

**Pull request merged**
