### PR TITLE
Add monaco code editor

### PR DESCRIPTION
**Pull request by MahmoudHamdy02**

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
Is there some reason behind not choosing Patternfly https://www.patternfly.org/components/code-editor ?

**Comment by MahmoudHamdy02** [comment]
Patternfly needs a webpack plugin: https://www.npmjs.com/package/@patternfly/react-code-editor#:~:text=%22monaco%2Deditor%2Dwebpack%2Dplugin%22%3A%20%22%5E2.1.0%22

**Comment by KKoukiou** [comment]
> Patternfly needs a webpack plugin: https://www.npmjs.com/package/@patternfly/react-code-editor#:~:text=%22monaco%2Deditor%2Dwebpack%2Dplugin%22%3A%20%22%5E2.1.0%22

Did you try it though? Because I don't see these peer dependencies listed in the package.json file https://github.com/patternfly/patternfly-react/blob/main/packages/react-code-editor/package.json#L38

**Review by KKoukiou — COMMENTED** [review]
This has some CSP issues as you currently figured out. See https://github.com/KKoukiou/cockpit-navigator/pull/83#issue-1858313408 for details.

Try using the monaco-editor/react which looks like addressed already these issues.

**Comment by allisonkarlitskaya** [comment]
This is not planned — mostly do to how large this component is and the CSP issues introduced by loading content from the CDN.  We will add a simple editor based on TextArea for the time being.

**Pull request closed without merging**
