### PR TITLE
Fix width of the sidebar panel

### PR DESCRIPTION
**Pull request by tomasmatus**

### CODE REVIEW

**Comment by tomasmatus** [comment]
Still problematic on narrow medium screens

image

**Comment by jelly** [comment]
@tomasmatus does this still need work?

**Comment by tomasmatus** [comment]
@jelly yes, I couldn't figure it out

**Comment by jelly** [comment]
@garrett is working on the layout which hopefully resolves this, so closing.

**Comment by garrett** [comment]
I made some changes that mostly fixed this in a previous PR, at #493.

But it should be fully fixed in #506, now ready for review.

**Pull request closed without merging**
