### PR TITLE
Add create file button

### LINKED ISSUE #103: add 'create file' button

### PR DESCRIPTION
**Pull request by MahmoudHamdy02**
Closes #103

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
See https://github.com/KKoukiou/cockpit-navigator/issues/103#issuecomment-1704863596 

How did this issue come up actually? Was it requested or was your idea?

**Comment by MahmoudHamdy02** [comment]
It was in the mockups. We can delay this until we have an editor though

**Comment by allisonkarlitskaya** [comment]
Something like this will definitely be useful in combination with a text editor...

**Comment by jelly** [comment]
This needs some UX discussion, started them here https://issues.redhat.com/browse/COCKPIT-1162

**Pull request closed without merging**
